[versions]
assertj = "3.23.1"
# @pin
aws2 = "2.18.4"
bouncycastle = "1.70"
docker = "3.3.0"
grpc = "1.53.0"
hoplite = "2.7.1"
jackson = "2.14.2"
jnrUnixsocket = "0.38.19"
junit = "5.9.2"
kotest = "5.5.5"
# @pin
kotlin = "1.7.22"
kotlinBinaryCompatibilityPlugin = "0.12.1"
kotlinLogging = "3.0.5"
kotlinRetry = "1.0.9"
kotlinx = "1.6.4"
# @pin
launchDarkly = "5.10.6"
logback = "1.4.5"
# @pin
mavenPublishGradlePlugin = "0.23.2"
# @pin
micrometer = "1.9.2"
mockito = "4.9.0"
moshi = "1.14.0"
netty = "4.1.89.Final"
okHttp = "4.10.0"
okio = "3.3.0"
openTracing = "0.33.0"
openTracingOkHttp = "3.0.0"
protobufGradlePlugin = "0.9.2"
slf4j = "2.0.6"
versionCatalogUpdateGradlePlugin = "0.7.0"
versionsGradlePlugin = "0.45.0"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
aws2Bom = { module = "software.amazon.awssdk:bom", version.ref = "aws2" }
aws2Regions = { module = "software.amazon.awssdk:regions" } # omit the version so attempts to use this dep without the BOM fail
bouncycastle = { module = "org.bouncycastle:bcprov-jdk15on", version.ref = "bouncycastle" }
dockerCore = { module = "com.github.docker-java:docker-java-core", version.ref = "docker" }
dockerTransport = { module = "com.github.docker-java:docker-java-transport-httpclient5", version.ref = "docker" }
grpcBom = { module = "io.grpc:grpc-bom", version.ref = "grpc" }
hopliteCore = { module = "com.sksamuel.hoplite:hoplite-core", version.ref = "hoplite" }
hopliteHocon = { module = "com.sksamuel.hoplite:hoplite-hocon", version.ref = "hoplite" }
hopliteJson = { module = "com.sksamuel.hoplite:hoplite-json", version.ref = "hoplite" }
hopliteToml = { module = "com.sksamuel.hoplite:hoplite-toml", version.ref = "hoplite" }
hopliteYaml = { module = "com.sksamuel.hoplite:hoplite-yaml", version.ref = "hoplite" }
jacksonBom = { module = "com.fasterxml.jackson:jackson-bom", version.ref = "jackson" }
jnrUnixsocket = { module = "com.github.jnr:jnr-unixsocket", version.ref = "jnrUnixsocket" }
junitApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junitEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
kotestAssertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotestJunitRunnerJvm = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
kotestProperty = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotlinBom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlinRetry = { module = "com.michael-bull.kotlin-retry:kotlin-retry", version.ref = "kotlinRetry" }
kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx" }
launchDarkly = { module = "com.launchdarkly:launchdarkly-java-server-sdk", version.ref = "launchDarkly" }
logbackClassic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
loggingApi = { module = "io.github.microutils:kotlin-logging", version.ref = "kotlinLogging" }
micrometerPrometheus = { module = "io.micrometer:micrometer-registry-prometheus", version.ref = "micrometer" }
mockitoCore = { module = "org.mockito:mockito-core", version.ref = "mockito" }
moshiAdapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
moshiCore = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshiKotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
nettyBom = { module = "io.netty:netty-bom", version.ref = "netty" }
okHttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okHttp" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
openTracing = { module = "io.opentracing:opentracing-api", version.ref = "openTracing" }
openTracingMock = { module = "io.opentracing:opentracing-mock", version.ref = "openTracing" }
openTracingOkHttp = { module = "io.opentracing.contrib:opentracing-okhttp3", version.ref = "openTracingOkHttp" }
slf4jApi = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

[bundles]
hoplite = [
    "hopliteCore",
    "hopliteHocon",
    "hopliteJson",
    "hopliteToml",
    "hopliteYaml",
]
kotest = [
    "kotestAssertions",
    "kotestJunitRunnerJvm",
    "kotestProperty",
]

[plugins]
kotlinBinaryCompatibilityPlugin = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlinBinaryCompatibilityPlugin" }
kotlinGradlePlugin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
mavenPublishGradlePlugin = { id = "com.vanniktech.maven.publish.base", version.ref = "mavenPublishGradlePlugin" }
protobufGradlePlugin = { id = "com.google.protobuf", version.ref = "protobufGradlePlugin" }
versionCatalogUpdateGradlePlugin = { id = "nl.littlerobots.version-catalog-update", version.ref = "versionCatalogUpdateGradlePlugin" }
versionsGradlePlugin = { id = "com.github.ben-manes.versions", version.ref = "versionsGradlePlugin" }
