name: Master

on:
  push:
    branches:
      - master

env:
  ENVIRONMENT: TESTING
  JVM_OPTS: -Xmx1024M
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=3 -Xmx4096m -Dorg.gradle.configureondemand=true -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx4096m -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
  TERM: dumb

jobs:
  js:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12]
        cmd:
          - sudo npm install -g @misk/cli && miskweb ci-build -e

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: ${{ matrix.cmd }}

  jvm:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        cmd:
          - ./gradlew testShardHibernate -i --scan
          - ./gradlew testShardNonHibernate -i --scan --parallel

    steps:
      - name: Setup SQL to reset Mysql root password for tests
        run: |
          echo 'mysql_pwd_clear<<EOF' >> $GITHUB_ENV
          echo "ALTER USER 'root'@'localhost' IDENTIFIED BY '';" >> $GITHUB_ENV
          echo 'FLUSH PRIVILEGES;' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Start MySQL and reset root password
        run: |
          sudo /etc/init.d/mysql restart
          mysql -uroot -proot -e "${{ env.mysql_pwd_clear }}"
          sudo /etc/init.d/mysql restart

      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Configure JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11.0.11+9

      - name: Test
        run: ${{ matrix.cmd }}

      - name: Publish Test Report
        if: ${{ always() }}
        uses: mikepenz/action-junit-report@v2
        with:
          check_name: Test Report - ${{ matrix.cmd }}
          report_paths: '**/build/test-results/test/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
